version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: medilink-laboratory-db
    environment:
      POSTGRES_DB: medilink_laboratory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - laboratory_data:/var/lib/postgresql/data
    networks:
      - laboratory-network

volumes:
  laboratory_data:

networks:
  laboratory-network:
    driver: bridge
