sonar.projectKey=medilink-tunisia
sonar.projectName=MediLink Tunisia - Smart Health Tunisia
sonar.projectVersion=1.0.0

sonar.sources=Backend,Frontend/medilink-angular/src
sonar.tests=Backend,Frontend/medilink-angular/src
sonar.test.inclusions=**/*Test*.java,**/*Spec*.ts,**/*spec*.ts

sonar.java.binaries=Backend/api-gateway/target/classes,Backend/auth-service/target/classes,Backend/config-server/target/classes,Backend/doctor-service/target/classes,Backend/eureka-service/target/classes,Backend/patient-service/target/classes,Backend/pharmacy-service/target/classes,Backend/prescription-service/target/classes

sonar.javascript.lcov.reportPaths=Frontend/medilink-angular/coverage/lcov.info
sonar.typescript.lcov.reportPaths=Frontend/medilink-angular/coverage/lcov.info

sonar.coverage.jacoco.xmlReportPaths=Backend/api-gateway/target/site/jacoco/jacoco.xml,Backend/auth-service/target/site/jacoco/jacoco.xml,Backend/config-server/target/site/jacoco/jacoco.xml,Backend/doctor-service/target/site/jacoco/jacoco.xml,Backend/eureka-service/target/site/jacoco/jacoco.xml,Backend/patient-service/target/site/jacoco/jacoco.xml,Backend/pharmacy-service/target/site/jacoco/jacoco.xml,Backend/prescription-service/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/target/**,**/*.log,**/logs/**,**/.angular/**,**/dist/**,**/*.pdf,**/environments/**,**/resources/application*.yml,**/resources/application*.properties,**/*Config.java
sonar.coverage.exclusions=**/*Application.java,**/*Config.java,**/config/**,**/dto/**,**/model/**,**/enums/**,**/*Request.java,**/*Response.java,**/*Dto.java,**/*Exception.java

sonar.host.url=https://sonarcloud.io
sonar.organization=medilink-tunisia

sonar.language=java,ts,js
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
