apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      timeInterval: 15s
      queryTimeout: 30s
      httpMethod: POST

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    database: medilink_monitoring
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: true
    uid: postgres
